version: '3'
services:
  database:
    image: postgres:11
    container_name: trainee-fut
    ports:
      - 7777:5432
    environment:
      POSTGRES_DB: fut
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sg